### ISSUE TITLE
Pass children within block

### ISSUE THREAD

**Issue by grzegorz-jakubiak** [prism-rb/prism#12]
I feel like this syntax is more natural to ruby and people are more used to it.
```ruby
div(".hello-world") do
  input(onInput :call(:name=).with_target_data(:value))
  div("Hello, #{name}")
end
```

**Comment by Widdershin** [comment]
I'd be fine to have this style as an optional module you could include when using `Prism` but I'm not sure I'm convinced that the complexity required to implement it is worth including it everywhere.

I am also not huge on the element helpers having side effects, just from a code predictability perspective.

**Comment by grzegorz-jakubiak** [comment]
I totally get it. I also remembered some problems with `content_tag`s having multiple children so I'm closing the issue.
