### ISSUE TITLE
Consider targeting both mruby and Opal

### ISSUE THREAD

**Issue by elia** [prism-rb/prism#16]
_(disclaimer: I'm the maintainer of [Opal](https://opalrb.com))_

Would be possible for Prism to target both mruby and Opal? 
Opal is really mature and would be great to be able to use Prism as frontend framework.

**Comment by Widdershin** [comment]
I don’t know enough about Opal to really say whether or not it would be possible, but I can’t immediately think of any benefits from doing so that would justify the complexity.

You’re welcome to use the Prism code to make something similar on top of Opal if you like.
