### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by grzegorz-jakubiak** [prism-rb/prism#19]
Have you thought about adding Ruby tests for all of the prism classes? Maybe you'd like to also add some tests for C and javascript parts. We could set up travis for that.

**Comment by Widdershin** [comment]
Yes to all of above. I would personally be most interested in starting with some end to end tests, as there’s so many moving pieces. 

Additionally, the design is likely to change quite a bit but end to end tests will always be useful

**Comment by Widdershin** [comment]
We now have `scripts/run-tests` and `tests/js_bindings_test.rb` on the master branch.

These tests run in a headless browser and have CLI reporting.
