### ISSUE TITLE
Improve error message when the application doesn't return a mount

### ISSUE THREAD

**Issue by Widdershin** [prism-rb/prism#2]

**Comment by grzegorz-jakubiak** [comment]
Hi there! I could work on that :smiley: Just let me know what help you need :wink:

**Comment by Widdershin** [comment]
That would be wonderful.

I was thinking of adding something to the ‘load’ function in main.c that
uses an mruby function to check the type of ‘app’ is a ‘Prism::Mountpoint’.
The best docs for mruby’s c api are in the ‘mruby.h’. Let me know if you
need more to go on!

**Comment by grzegorz-jakubiak** [comment]
Thanks I'll give it a go although my C is a bit rusty.
I'd need to know how to build the project I don't see any information bout it :wink:

**Comment by Widdershin** [comment]
Closed by 1371a4ee28455418dec44813dd19465a6fcedcc0
