### ISSUE TITLE
Problem running prism-cli on the commandline

### ISSUE THREAD

**Issue by rubyFeedback** [prism-rb/prism#27]
I did:

> prism init

Output was:

"Created new Prism app at app.rb

Run prism server to see your app."

Then I did:

> prism server

And got an error:

    internal/modules/cjs/loader.js:883
      throw err;
      ^

    Error: Cannot find module '/usr/wasm-server.js'
        at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
        at Function.Module._load (internal/modules/cjs/loader.js:725:27)
        at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
        at internal/main/run_main_module.js:17:47 {
      code: 'MODULE_NOT_FOUND',
      requireStack: []
    }

The path looks a bit weird to me. /usr/wasm-server.js ? Is this
hardcoded? When I do "init" then perhaps all js files
should be in the current working directory? Not sure, this is
actually a genuine question - first time trying out prism.

By the way great that it exists - WASM sounds interesting but
I did not invest a lot of time into it so far.

**Comment by Widdershin** [comment]
Thanks for the bug report, I'll take a look at this in the next few days.
