### ISSUE TITLE
Building Prism app

### ISSUE THREAD

**Issue by Jomy10** [prism-rb/prism#29]
Hello

I've been playing around with Prism, and I really like it so far. However, it doesn't seem like `prism build` has been implemented yet? How can I build the app so I can put it on a server?

**Comment by Jomy10** [comment]
I've managed to figure out the steps that have to be taken to get this to work. It would be nice to have some clearer documentation or something, but of course this project is still in its infancy. I really enjoy creating something with prism.

**Comment by Widdershin** [comment]
Hi @Jomy10,

Yeah sorry about the state of the docs, this project is in super active development at the moment. Aiming to do a big overhaul of the docs soon, but I'm also making breaking changes on a day-to-day basis.

Will update this issue once things are a bit more stable.
