### ISSUE TITLE
Setting listen address in prism server

### ISSUE THREAD

**Issue by DannyBen** [prism-rb/prism#8]
I see there is no way to change the listen address of the `prism server` command from`localhost`.

In some situations, `localhost` is not an option, and needs to be `0.0.0.0`.

I see `127.0.0.1` is hardcoded:

https://github.com/prism-rb/prism/blob/21af933aa79d96a3db8a4faf70546d38e13965b0/wasm-server.js#L104

I think this needs to change. Are you open to accept a PR to fix this?

**Comment by Widdershin** [comment]
Closed by `cbe6e70d4`
